name: CI/CD Despliegue con Docker Hub y Render

on:
  push:
    branches:
      - main  # Ejecutar al hacer push a la rama 'main'

env:
  # Imagen final en Docker Hub
  DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/regulatory-report-app
  REGISTRY: docker.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: 拘勇 Checkout del C칩digo
        uses: actions/checkout@v4

      # 1. Iniciar sesi칩n en Docker Hub usando el PAT
      - name: 游냡 Iniciar sesi칩n en Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 2. Construir y Subir la Imagen (Evidencia de Construcci칩n y Push)
      - name: 游 Construir, Etiquetar y Subir a Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: . # Usa el Dockerfile en la ra칤z
          push: true
          # Etiquetado con 'latest' y el hash del commit para control de versiones
          tags: |
            ${{ env.DOCKER_REPO }}:latest
            ${{ env.DOCKER_REPO }}:${{ github.sha }}

      # 3. Gu칤a para Render
      - name: 丘뙖잺 Gu칤a para Render
        run: |
          echo "La imagen se ha subido a Docker Hub como: ${{ env.DOCKER_REPO }}:latest"
          echo "La imagen est치 lista para ser descargada por Render."
          echo "Tu siguiente paso es ir a Render y crear el servicio web usando esa URL."